---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
---
server:
    contextPath: /stock

dataSource:
    pooled: true
    dbCreate: 'update'
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/rishiqing-stock?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    #username: mailuser
    #password: ttm&qIU(@
    #url: jdbc:mysql://10.170.234.110:3306/rishiqing-stock?autoReconnect=true&characterEncoding=utf-8&useSSL=false

    #username: root
    #password: admin
    #url: jdbc:mysql://localhost:3306/rishiqing-stock?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    #logSql: true
    #formatSql: true
    properties:
        maxActive: -1
        minEvictableIdleTimeMillis: 1800000
        timeBetweenEvictionRunsMillis: 1800000
        numTestsPerEvictionRun: 3
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: true
        validationQuery: SELECT 1
---
---
grails:
    profile: web
    codegen:
        defaultPackage: rishiqing.stock
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
server:
    session.timeout = 7200
